### PR TITLE
Alphabetise the list

### PR DESCRIPTION
**Pull request by jakemulley**
This PR:

- Alphabetises the list of acronyms

### CODE REVIEW

**Review by digitalronin — COMMENTED** [review]
I like the idea of this. How did you do the sorting? If I open up this version of the README in vim, and do a `!sort` on the list content, I get some changes.

**Comment by jakemulley** [comment]
> I like the idea of this. How did you do the sorting? If I open up this version of the README in vim, and do a `!sort` on the list content, I get some changes.

I did it via Sublime and Sort Lines, which is case insensitive, but IIRC !sort is case sensitive by default unless you use the `i` flag.

**Comment by digitalronin** [comment]
I was getting very confused until I actually read the man page for sort! It's `-f` or `--ignore-case`

Given that we have a repeatable strategy that works for all users, I'm happy to go ahead with this. It would be nice if the sorting were applied by a github action on every change, but we can leave that for another day!

**Review by digitalronin — APPROVED** [review]

**Comment by jakemulley** [comment]
Ha, no worries!

**Pull request merged**
